version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./schema.sql:/schema.sql
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5432
  app:
    container_name: payments_go_app
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "./wait-for-it.sh db:5432 -- go build main.go && ./main"
    volumes:
      - .:/go/src/github.com/nitrajka/paymentsFutured
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
