// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"time"
)

type Payment struct {
	ID          int32     `json:"id"`
	Amount      float64   `json:"amount"`
	Description string    `json:"description"`
	Sender      string    `json:"sender"`
	Datetime    time.Time `json:"datetime"`
}
